"""steadyhand: a market-neutral engine for self-hosted, dividend-first portfolio bots."""

from importlib.metadata import version

from steadyhand.backtest import (
    BacktestResult,
    BacktestSettings,
    Market,
    NoTradingDaysError,
    RunResult,
    UniverseCoverageError,
    backtest,
)
from steadyhand.broker import Broker, FillResult, FillSettings, Opening, SimulatedBroker
from steadyhand.corporate import (
    PAY_LAG_TRADING_DAYS,
    CorporateOutcome,
    Entitlement,
    Holdings,
    apply_actions,
)
from steadyhand.data import DataSource, DataUnavailableError, UnavailableDaysError
from steadyhand.disclaimer import DISCLAIMER
from steadyhand.engine import (
    DataValidationError,
    DayInputs,
    DayOrderError,
    DayReport,
    EngineSettings,
    EngineState,
    run_day,
)
from steadyhand.income import (
    BASE_GROWTH_CAP,
    GROWTH_YEARS,
    OPTIMISTIC_GROWTH_CAP,
    PESSIMISTIC_START,
    PROJECTION_LABEL,
    PROJECTION_MONTHS,
    DividendGrowth,
    HoldingCalendar,
    HoldingGrowth,
    HoldingRunRate,
    IncomeFigures,
    IncomeGoal,
    IncomeSettings,
    MonthlyIncome,
    PaymentCalendar,
    Projection,
    ProjectionOutcome,
    ReceivedIncome,
    RunRate,
    Scenario,
    ScenarioProjection,
    dividend_growth,
    payment_calendar,
    project,
    received_income,
    run_rate,
    years_before,
)
from steadyhand.market import MarketRules, UnsupportedDateError, add_trading_days
from steadyhand.metrics import (
    RATIO_PLACES,
    YEAR_DAYS,
    CostBreakdown,
    DividendTotals,
    Drawdown,
    Metrics,
    measure,
    year_window_start,
)
from steadyhand.money import (
    IDR,
    MAX_MINOR_UNITS,
    Currency,
    CurrencyMismatchError,
    Money,
    Rounding,
)
from steadyhand.notes import INCOME_GROWTH_SHORT_HISTORY, INCOME_PROJECTION_COSTS_IGNORED, Note
from steadyhand.outcomes import Cut, Rejected
from steadyhand.portfolio import (
    CashMovement,
    ChronologyError,
    InsufficientCashError,
    InsufficientSharesError,
    MissingPriceError,
    MovementKind,
    NegativeProceedsError,
    Portfolio,
)
from steadyhand.risk import Checked, Halt, RiskLimits, RiskManager, UnitValue
from steadyhand.sizing import CompoundingSizer, Sizer
from steadyhand.strategies import (
    STRATEGIES,
    BuyAndHold,
    Decision,
    InvalidWeightsError,
    Memory,
    Strategy,
)
from steadyhand.types import (
    Bar,
    CashDividend,
    CorporateAction,
    Costs,
    Fill,
    Instrument,
    InvalidBarError,
    Order,
    OrderAck,
    OtherAction,
    Position,
    Side,
    Split,
)
from steadyhand.universe import Universe
from steadyhand.view import LookAheadError, MarketView, PortfolioView, PriceHistory, Tradable

__version__: str = version("steadyhand")

__all__ = [
    "BASE_GROWTH_CAP",
    "DISCLAIMER",
    "GROWTH_YEARS",
    "IDR",
    "INCOME_GROWTH_SHORT_HISTORY",
    "INCOME_PROJECTION_COSTS_IGNORED",
    "MAX_MINOR_UNITS",
    "OPTIMISTIC_GROWTH_CAP",
    "PAY_LAG_TRADING_DAYS",
    "PESSIMISTIC_START",
    "PROJECTION_LABEL",
    "PROJECTION_MONTHS",
    "RATIO_PLACES",
    "STRATEGIES",
    "YEAR_DAYS",
    "BacktestResult",
    "BacktestSettings",
    "Bar",
    "Broker",
    "BuyAndHold",
    "CashDividend",
    "CashMovement",
    "Checked",
    "ChronologyError",
    "CompoundingSizer",
    "CorporateAction",
    "CorporateOutcome",
    "CostBreakdown",
    "Costs",
    "Currency",
    "CurrencyMismatchError",
    "Cut",
    "DataSource",
    "DataUnavailableError",
    "DataValidationError",
    "DayInputs",
    "DayOrderError",
    "DayReport",
    "Decision",
    "DividendGrowth",
    "DividendTotals",
    "Drawdown",
    "EngineSettings",
    "EngineState",
    "Entitlement",
    "Fill",
    "FillResult",
    "FillSettings",
    "Halt",
    "HoldingCalendar",
    "HoldingGrowth",
    "HoldingRunRate",
    "Holdings",
    "IncomeFigures",
    "IncomeGoal",
    "IncomeSettings",
    "Instrument",
    "InsufficientCashError",
    "InsufficientSharesError",
    "InvalidBarError",
    "InvalidWeightsError",
    "LookAheadError",
    "Market",
    "MarketRules",
    "MarketView",
    "Memory",
    "Metrics",
    "MissingPriceError",
    "Money",
    "MonthlyIncome",
    "MovementKind",
    "NegativeProceedsError",
    "NoTradingDaysError",
    "Note",
    "Opening",
    "Order",
    "OrderAck",
    "OtherAction",
    "PaymentCalendar",
    "Portfolio",
    "PortfolioView",
    "Position",
    "PriceHistory",
    "Projection",
    "ProjectionOutcome",
    "ReceivedIncome",
    "Rejected",
    "RiskLimits",
    "RiskManager",
    "Rounding",
    "RunRate",
    "RunResult",
    "Scenario",
    "ScenarioProjection",
    "Side",
    "SimulatedBroker",
    "Sizer",
    "Split",
    "Strategy",
    "Tradable",
    "UnavailableDaysError",
    "UnitValue",
    "Universe",
    "UniverseCoverageError",
    "UnsupportedDateError",
    "__version__",
    "add_trading_days",
    "apply_actions",
    "backtest",
    "dividend_growth",
    "measure",
    "payment_calendar",
    "project",
    "received_income",
    "run_day",
    "run_rate",
    "year_window_start",
    "years_before",
]
